#!/bin/bash

red="\033[31m"
green="\033[32m"
default="\033[37m"

echo ''
read -p "Enter directory name: " directoryName


if ! [ -d $directoryName ]
then
echo -e "\nDirectory $red $directoryName $default not found. Create directore $directoryName"
git init $directoryName
fi



